//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("binary console like in movies")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+c1771603aa6e4ed461e24c5ec2f32d5b8aacc823")]
[assembly: System.Reflection.AssemblyProductAttribute("binary console like in movies")]
[assembly: System.Reflection.AssemblyTitleAttribute("binary console like in movies")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Von der MSBuild WriteCodeFragment-Klasse generiert.

